/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package pedidos.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.MappingDispatchAction;

import pedidos.ejercicio.model.Categoria;
import pedidos.ejercicio.model.Item;
import pedidos.services.PedidosServer;
import pedidos.struts.form.ItemForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-19-2012
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ItemAction extends MappingDispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward newItem(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String fwd = "goNew";
		PedidosServer pserver = new PedidosServer();
		request.setAttribute("categorias", pserver.listarCategorias());
		System.out.println("newItem");		
		return mapping.findForward(fwd);
	}
	
	public ActionForward showItem(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String fwd = "goShow";
		PedidosServer pserver = new PedidosServer();
		
		
		if (request.getParameter("cbCategoria")!=null){
			Integer idCat = new Integer( request.getParameter("cbCategoria"));		
			request.setAttribute("items", pserver.listarItemByCategoria(idCat));	
			System.out.println("ID CAT showItem getParameter" + idCat);
		}else{
			request.setAttribute("items", pserver.listarItems());
		}
		
		System.out.println("showItem");
		return mapping.findForward(fwd);
	}
	
	
	public ActionForward guardarItem(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ItemForm newItemForm = (ItemForm) form;// TODO Auto-generated method stub
		String fwd = "goShow";
		PedidosServer pserver = new PedidosServer();			
		Categoria cat = pserver.buscarCategoria(newItemForm.getCategoria());
		Item it = new Item(cat,
						newItemForm.getNombre(),
						newItemForm.getDescripcion(),						
						newItemForm.getPrecioCompra(),
						newItemForm.getPrecioVenta(),
						newItemForm.getImagen());

		pserver.crearItem(it);	
		request.setAttribute("item", it);
		System.out.println("guardarItem");
		return mapping.findForward(fwd);
	}
	
	public ActionForward deleteItem(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String fwd = "goShow";
		PedidosServer pserver = new PedidosServer();
		Item it = pserver.buscarItem(new Integer(request.getParameter("id")));
		pserver.deleteItem(it);
		System.out.println("deleteItem");
		return mapping.findForward(fwd);
	}
	
	
}