/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package pedidos.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-19-2012
 * 
 * XDoclet definition:
 * @struts.form name="clienteForm"
 */
public class ClienteForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** apellido property */
	private String apellido;

	/** nombre property */
	private String nombre;

	/** direccion property */
	private String direccion;

	/** ciudad property */
	private String ciudad;

	/** telefono property */
	private String telefonos;

	/** cedula property */
	private String cedula;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the apellido.
	 * @return String
	 */
	public String getApellido() {
		return apellido;
	}

	/** 
	 * Set the apellido.
	 * @param apellido The apellido to set
	 */
	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	/** 
	 * Returns the nombre.
	 * @return String
	 */
	public String getNombre() {
		return nombre;
	}

	/** 
	 * Set the nombre.
	 * @param nombre The nombre to set
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/** 
	 * Returns the direccion.
	 * @return String
	 */
	public String getDireccion() {
		return direccion;
	}

	/** 
	 * Set the direccion.
	 * @param direccion The direccion to set
	 */
	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	/** 
	 * Returns the ciudad.
	 * @return String
	 */
	public String getCiudad() {
		return ciudad;
	}

	/** 
	 * Set the ciudad.
	 * @param ciudad The ciudad to set
	 */
	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	/** 
	 * Returns the telefono.
	 * @return String
	 */
	public String getTelefono() {
		return telefonos;
	}

	/** 
	 * Set the telefono.
	 * @param telefono The telefono to set
	 */
	public void setTelefono(String telefonos) {
		this.telefonos = telefonos;
	}

	/** 
	 * Returns the cedula.
	 * @return String
	 */
	public String getCedula() {
		return cedula;
	}

	/** 
	 * Set the cedula.
	 * @param cedula The cedula to set
	 */
	public void setCedula(String cedula) {
		this.cedula = cedula;
	}
}