/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package pedidos.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;



/** 
 * MyEclipse Struts
 * Creation date: 12-19-2012
 * 
 * XDoclet definition:
 * @struts.form name="itemForm"
 */
public class ItemForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** nombre property */
	private String nombre;

	/** imagen property */
	private String imagen;

	/** descripcion property */
	private String descripcion;

	/** precioVenta property */
	private Double precioVenta;

	/** precioCompra property */
	private Double precioCompra;

	private Integer categoria;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		ActionErrors errores= new ActionErrors();
		if(nombre==null || nombre.equals("")){
			errores.add("nombre",new ActionMessage("empty.nombre"));
		}
		if(descripcion==null || descripcion.equals("")){
			errores.add("descripcion",new ActionMessage("empty.descripcion"));
		}
		if(categoria==null || categoria<=0){
			errores.add("categoria",new ActionMessage("empty.categoria"));
		}
		if(imagen==null || imagen.equals("")){
			errores.add("imagen",new ActionMessage("empty.imagen"));
		}
		if(precioCompra==null || precioCompra<=0){
			errores.add("precioCompra",new ActionMessage("empty.precioCompra"));
		}
		if(precioVenta==null || precioVenta<=0){
			errores.add("precioVenta",new ActionMessage("empty.precioVenta"));
		}
		
		return errores;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the nombre.
	 * @return String
	 */
	public String getNombre() {
		return nombre;
	}

	/** 
	 * Set the nombre.
	 * @param nombre The nombre to set
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/** 
	 * Returns the imagen.
	 * @return String
	 */
	public String getImagen() {
		return imagen;
	}

	/** 
	 * Set the imagen.
	 * @param imagen The imagen to set
	 */
	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	/** 
	 * Returns the descripcion.
	 * @return String
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/** 
	 * Set the descripcion.
	 * @param descripcion The descripcion to set
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/** 
	 * Returns the precioVenta.
	 * @return Double
	 */
	public Double getPrecioVenta() {
		return precioVenta;
	}

	/** 
	 * Set the precioVenta.
	 * @param precioVenta The precioVenta to set
	 */
	public void setPrecioVenta(Double precioVenta) {
		this.precioVenta = precioVenta;
	}

	/** 
	 * Returns the precioCompra.
	 * @return Double
	 */
	public Double getPrecioCompra() {
		return precioCompra;
	}

	/** 
	 * Set the precioCompra.
	 * @param precioCompra The precioCompra to set
	 */
	public void setPrecioCompra(Double precioCompra) {
		this.precioCompra = precioCompra;
	}

	public Integer getCategoria() {
		// TODO Auto-generated method stub
		return categoria;
	}
	
	public void setCategoria(Integer categoria) {
		this.categoria = categoria;
	}
	
	
}