/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package pedidos.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 12-21-2012
 * 
 * XDoclet definition:
 * @struts.form name="pagoForm"
 */
public class PagoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** propietario property */
	private String propietario;

	/** fechaPago property */
	private String fechaPago;

	/** monto property */
	private Double monto;
	
	/** pedido property */
	private Integer pedido;

	/*
	 * Generated Methods
	 */

	public Integer getPedido() {
		return pedido;
	}

	public void setPedido(Integer pedido) {
		this.pedido = pedido;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		ActionErrors errores= new ActionErrors();
		if(propietario==null || propietario.equals("")){
			errores.add("propietario",new ActionMessage("empty.propietario"));
		}
		if(fechaPago==null || fechaPago.equals("")){
			errores.add("fechaPago",new ActionMessage("empty.fechaPago"));
		}
		if(monto==null || monto<=0){
			errores.add("monto",new ActionMessage("empty.monto"));
		}
		if(pedido==null || pedido<=0){
			errores.add("pedido",new ActionMessage("pedido.monto"));
		}
		
		return errores;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the propietario.
	 * @return String
	 */
	public String getPropietario() {
		return propietario;
	}

	/** 
	 * Set the propietario.
	 * @param propietario The propietario to set
	 */
	public void setPropietario(String propietario) {
		this.propietario = propietario;
	}

	/** 
	 * Returns the fechaPago.
	 * @return String
	 */
	public String getFechaPago() {
		return fechaPago;
	}

	/** 
	 * Set the fechaPago.
	 * @param fechaPago The fechaPago to set
	 */
	public void setFechaPago(String fechaPago) {
		this.fechaPago = fechaPago;
	}

	/** 
	 * Returns the monto.
	 * @return Double
	 */
	public Double getMonto() {
		return monto;
	}

	/** 
	 * Set the monto.
	 * @param monto The monto to set
	 */
	public void setMonto(Double monto) {
		this.monto = monto;
	}
}