/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package pedidos.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 12-20-2012
 * 
 * XDoclet definition:
 * @struts.form name="PedidoForm"
 */
public class PedidoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** fecha property */
	private String fecha;

	/** cliente property */
	private Integer cliente;

	/** estatus property */
	private String estatus;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		ActionErrors errores= new ActionErrors();
		
		if(estatus==null || estatus.equals("")){
			errores.add("estatus",new ActionMessage("empty.estatus"));
		}
		if(cliente==null || cliente<=0){
			errores.add("cliente",new ActionMessage("empty.cliente"));
		}
		
		return errores;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the fecha.
	 * @return Date
	 */
	public String getFecha() {
		return fecha;
	}

	/** 
	 * Set the fecha.
	 * @param fecha The fecha to set
	 */
	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	/** 
	 * Returns the cliente.
	 * @return Integer
	 */
	public Integer getCliente() {
		return cliente;
	}

	/** 
	 * Set the cliente.
	 * @param cliente The cliente to set
	 */
	public void setCliente(Integer cliente) {
		this.cliente = cliente;
	}

	/** 
	 * Returns the estatus.
	 * @return String
	 */
	public String getEstatus() {
		return estatus;
	}

	/** 
	 * Set the estatus.
	 * @param estatus The estatus to set
	 */
	public void setEstatus(String estatus) {
		this.estatus = estatus;
	}
}